import os
import shutil
import base64
from tkinter import messagebox, Tk, Button, Label, Frame, filedialog, Entry, Listbox, END, SINGLE

# --- CÓDIGO DO ÍCONE (BASE64) ---
ICONE_VASSOURA_BASE64 = """
AAABAAEAQEAAAAEAIAAoQgAAFgAAACgAAABAAAAAgAAAAAEAIAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOwMt/zsDLf87Ay3/OwMt/zsDLf87Ay3/AAAAAAAAAAAAAAAAAAAAADsDLf87Ay3/OwMt/zsDLf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADsDLf87Ay3/OwMt/zsDLf87Ay3/OwMt/wAAAAAAAAAAAAAAAAAAAAA7Ay3/OwMt/zsDLf87Ay3/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADsDLf87Ay3/OwMt/zsDLf87Ay3/OwMt/zsDLf87Ay3/OwMt/zsDLf//3QD//90A///dAP//3QD//90A///dAP87Ay3/OwMt/zsDLf87Ay3//90A///dAP//3QD//90A/zsDLf87Ay3/AAAAAAAAAAA7Ay3/OwMt/zsDLf87Ay3/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7Ay3/OwMt/zsDLf87Ay3/OwMt/zsDLf87Ay3/OwMt/zsDLf87Ay3//90A///dAP//3QD//90A///dAP//3QD/OwMt/zsDLf87Ay3/OwMt///dAP//3QD//90A///dAP87Ay3/OwMt/wAAAAAAAAAAOwMt/zsDLf87Ay3/OwMt/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7Ay3/OwMt/zsDLf87Ay3//90A///dAP//3QD//90A///dAP//3QD//90A///dAP//3QD//90A///dAP//3QD/95j///eY//+j6P//o+j////zo///86P//90A///dAP//3QD//90A///zo///86P//90A///dAP87Ay3/OwMt///dAP//3QD//90A///dAP87Ay3/OwMt/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOwMt/zsDLf87Ay3/OwMt///dAP//3QD//90A///dAP//3QD//90A///dAP//3QD//90A///dAP//3QD//90A//eY///3mP//o+j//6Po////86P///Oj///dAP//3QD//90A///dAP//86P///Oj///dAP//3QD/OwMt/zsDLf//3QD//90A///dAP//3QD/OwMt/zsDLf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADsDLf87Ay3/95j///eY///3mP//95j////zo///86P///Oj///zo///86P///Oj///zo///86P//90A///dAP//3QD//90A//eY///3mP//o+j//6Po////86P///Oj///dAP//3QD///Oj///zo///86P///Oj///dAP//3QD///Oj///zo///86P///Oj///dAP//3QD/OwMt/zsDLf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7Ay3/OwMt//eY///3mP//95j///eY////86P///Oj///zo///86P///Oj///zo///86P///Oj///dAP//3QD//90A///dAP/3mP//95j//6Po//+j6P////Oj///zo///3QD//90A///zo///86P///Oj///zo///3QD//90A///zo///86P///Oj///zo///3QD//90A/zsDLf87Ay3/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7Ay3/OwMt/zsDLf87Ay3/95j///eY////86P///Oj///zo///86P///Oj///zo///86P///Oj///dAP//3QD/95j///eY///3mP//95j//6Po//+j6P///90A///dAP//86P///Oj///zo///86P//90A///dAP/3mP//95j////zo///86P///Oj///zo///3QD//90A/zsDLf87Ay3/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOwMt/zsDLf87Ay3/OwMt//eY///3mP////Oj///zo///86P///Oj///zo///86P///Oj///zo///3QD//90A//eY///3mP//95j///eY//+j6P//o+j////dAP//3QD///Oj///zo///86P///Oj///dAP//3QD/95j///eY////86P///Oj///zo///86P//90A///dAP87Ay3/OwMt/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7Ay3/OwMt//eY///3mP////Oj///zo//3mP//95j////zo///86P//90A///dAP//3QD//90A//eY///3mP//o+j//6Po////3QD//90A/6Po//+j6P////Oj///zo///3QD//90A//eY///3mP////Oj///zo///86P///Oj///zo///86P/OwMt/zsDLf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOwMt/zsDLf/3mP//95j////zo///86P/95j///eY////86P///Oj///dAP//3QD//90A///dAP/3mP//95j//6Po//+j6P///90A///dAP+j6P//o+j////zo///86P//90A///dAP/3mP//95j////zo///86P///Oj///zo///86P///Oj/zsDLf87Ay3/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOwMt/zsDLf/3mP//95j//6Po//+j6P//95j///eY////3QD//90A///dAP//3QD/95j///eY//+j6P//o+j////dAP//3QD/o+j//6Po////86P///Oj///dAP//3QD/95j///eY////86P///Oj/zsDLf87Ay3/OwMt/zsDLf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADsDLf87Ay3/95j///eY//+j6P//o+j///eY///3mP///90A///dAP//3QD//90A//eY///3mP//o+j//6Po////3QD//90A/6Po//+j6P////Oj///zo///3QD//90A//eY///3mP////Oj///zo/87Ay3/OwMt/zsDLf87Ay3/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7Ay3/OwMt//eY///3mP//o+j//6Po///3mP//95j//6Po//+j6P///90A///dAP/3mP//95j//6Po//+j6P//o+j//6Po//+j6P//o+j////dAP//3QD/95j///eY//+j6P//o+j///eY///3mP//OwMt/zsDLf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOwMt/zsDLf/3mP//95j//6Po//+j6P//95j///eY//+j6P//o+j////dAP//3QD/95j///eY//+j6P//o+j//6Po//+j6P//o+j//6Po////3QD//90A//eY///3mP//o+j//6Po///3mP//95j//zsDLf87Ay3/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADsDLf87Ay3/95j///eY//+j6P//o+j//6Po//+j6P//o+j//6Po////3QD//90A//eY///3mP//o+j//6Po//+j6P//o+j//6Po//+j6P///90A///dAP/3mP//95j//6Po//+j6P//OwMt/zsDLf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7Ay3/OwMt//eY///3mP//o+j//6Po//+j6P//o+j//6Po//+j6P///90A///dAP/3mP//95j//6Po//+j6P//o+j//6Po//+j6P//o+j////dAP//3QD/95j///eY//+j6P//o+j//zsDLf87Ay3/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOwMt/zsDLf/3mP//95j//6Po//+j6P//o+j//6Po//+j6P//o+j////dAP//3QD/o+j//6Po//+j6P//o+j//6Po//+j6P//o+j//6Po////3QD//90A//eY///3mP//o+j//6Po//87Ay3/OwMt/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADsDLf87Ay3/95j///eY//+j6P//o+j//6Po//+j6P//o+j//6Po////3QD//90A/6Po//+j6P//o+j//6Po//+j6P//o+j//6Po//+j6P///90A///dAP/3mP//95j//6Po//+j6P//OwMt/zsDLf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADsDLf87Ay3/o+j//6Po//+j6P//o+j//6Po//+j6P//o+j//6Po//+j6P//o+j//6Po//+j6P//o+j//6Po////3QD//90A/6Po//+j6P//o+j//6Po//87Ay3/OwMt/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7Ay3/OwMt/6Po//+j6P//o+j//6Po//+j6P//o+j//6Po//+j6P//o+j//6Po//+j6P//o+j//6Po//+j6P///90A///dAP+j6P//o+j//6Po//+j6P//OwMt/zsDLf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOwMt/zsDLf+j6P//o+j//zsDLf87Ay3/OwMt/zsDLf+j6P//o+j//6Po//+j6P//o+j//6Po//+j6P//o+j//6Po//+j6P//o+j//6Po//+j6P//o+j//zsDLf87Ay3/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADsDLf87Ay3/o+j//6Po//87Ay3/OwMt/zsDLf87Ay3/o+j//6Po//+j6P//o+j//6Po//+j6P//o+j//6Po//+j6P//o+j//6Po//+j6P//o+j//6Po//87Ay3/OwMt/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADsDLf87Ay3/AK7b/wCu2/8Artv/AK7b/zsDLf87Ay3/OwMt/zsDLf87Ay3/OwMt/6Po//+j6P//o+j//6Po//+j6P//o+j//zsDLf87Ay3/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7Ay3/OwMt/wCu2/8Artv/AK7b/wCu2/87Ay3/OwMt/zsDLf87Ay3/OwMt/zsDLf+j6P//o+j//6Po//+j6P//o+j//6Po//87Ay3/OwMt/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7Ay3/OwMt/2fg//9n4P//Z+D//2fg//9n4P//Z+D//wCu2/8Artv/OwMt/zsDLf87Ay3/OwMt/zsDLf87Ay3/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOwMt/zsDLf9n4P//Z+D//2fg//9n4P//Z+D//2fg//8Artv/AK7b/zsDLf87Ay3/OwMt/zsDLf87Ay3/OwMt/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADsDLf87Ay3/OwMt/zsDLf87Ay3/OwMt/zsDLf87Ay3/OwMt/zsDLf87Ay3/OwMt/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7Ay3/OwMt/zsDLf87Ay3/OwMt/zsDLf87Ay3/OwMt/zsDLf87Ay3/OwMt/zsDLf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADsDLf87Ay3/fwD//38A//9/AP//fwD//zsDLf87Ay3/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7Ay3/OwMt/38A//9/AP//fwD//38A//87Ay3/OwMt/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOwMt/zsDLf9/AP//fwD//zsDLf87Ay3/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADsDLf87Ay3/fwD//38A//87Ay3/OwMt/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOwMt/zsDLf9/AP//fwD//38A//9/AP//OwMt/zsDLf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADsDLf87Ay3/fwD//38A//9/AP//fwD//zsDLf87Ay3/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7Ay3/OwMt/38A//9/AP//OwMt/zsDLf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOwMt/zsDLf9/AP//fwD//zsDLf87Ay3/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7Ay3/OwMt/38A//9/AP//fwD//38A//87Ay3/OwMt/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOwMt/zsDLf9/AP//fwD//38A//9/AP//OwMt/zsDLf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADsDLf87Ay3/fwD//38A//9/AP//fwD//zsDLf87Ay3/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7Ay3/OwMt/38A//9/AP//fwD//38A//87Ay3/OwMt/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADsDLf87Ay3/fwD//38A//9/AP//fwD//zsDLf87Ay3/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7Ay3/OwMt/38A//9/AP//fwD//38A//87Ay3/OwMt/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOwMt/zsDLf9/AP//fwD//38A//9/AP//OwMt/zsDLf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADsDLf87Ay3/fwD//38A//9/AP//fwD//zsDLf87Ay3/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOwMt/zsDLf9/AP//fwD//38A//9/AP//OwMt/zsDLf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADsDLf87Ay3/fwD//38A//9/AP//fwD//zsDLf87Ay3/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7Ay3/OwMt/38A//9/AP//fwD//38A//87Ay3/OwMt/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOwMt/zsDLf9/AP//fwD//38A//9/AP//OwMt/zsDLf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7Ay3/OwMt/38A//9/AP//fwD//38A//87Ay3/OwMt/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOwMt/zsDLf9/AP//fwD//38A//9/AP//OwMt/zsDLf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADsDLf87Ay3/fwD//38A//9/AP//fwD//zsDLf87Ay3/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7Ay3/OwMt/38A//9/AP//fwD//38A//87Ay3/OwMt/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADsDLf87Ay3/fwD//38A//9/AP//fwD//zsDLf87Ay3/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7Ay3/OwMt/38A//9/AP//fwD//38A//87Ay3/OwMt/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOwMt/zsDLf9/AP//fwD//38A//9/AP//OwMt/zsDLf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADsDLf87Ay3/fwD//38A//9/AP//fwD//zsDLf87Ay3/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADsDLf87Ay3/OwMt/zsDLf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7Ay3/OwMt/zsDLf87Ay3/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/////////////////////////8Dw////////wPD//////wAAADD/////AAAAMP////AAAAAAP///8AAAAAA////wAAAAAA////AAAAAAD////AAAAAAD///8AAAAAAP////AAAAAA////8AAAAAD////8AAAAA/////wAAAAD/////AAAAA/////8AAAAD/////wAAAA//////AAAAD/////8AAAAP/////wAAAA//////wAAAP//////AAAA//////8AAAD//////wAAAP//////wAAD///////AAAP///////AAD///////8AAP///////wAP////////AA////////wD/////////AP////////8D/////////wP////////8A/////////wD/////////A/////////8D/////////AP////////8A/////////wD/////////AP////////wD/////////AP////////8A/////////wD////////8A/////////wD/////////AP////////8A/////////AP////////8A/////////wD/////////AP////////wD/////////AP////////8A/////////wD/////////w//////////D////////////////////////////8=

"""

# --- BANCO DE DADOS DE TAGS COMUNS ---
PRESETS = {
    "Vídeos": ".mp4, .mkv, .avi, .mov, .wmv, .flv",
    "Fotos": ".jpg, .jpeg, .jfif, .png, .gif, .webp, .svg, .bmp",
    "Músicas": ".mp3, .wav, .flac, .ogg, .m4a",
    "Documentos": ".pdf, .docx, .txt, .xlsx, .pptx, .csv",
    "Compactados": ".zip, .rar, .7z, .tar, .gz, .bz2",
    "Instaladores/Sist": ".exe, .msi, .iso, .msu, .bat, .jar"
}

TODAS_EXTENSOES = []
for lista in PRESETS.values():
    TODAS_EXTENSOES.extend([ext.strip() for ext in lista.split(',')])
TODAS_EXTENSOES = list(set(TODAS_EXTENSOES))

regras_usuario = {}


# --- FUNÇÕES DE LÓGICA ---

def auto_scan():
    caminho = lbl_caminho.cget("text")
    if not os.path.exists(caminho) or caminho == "Nenhuma pasta selecionada":
        messagebox.showwarning("Aviso", "Selecione uma pasta alvo primeiro!")
        return

    arquivos = [f for f in os.listdir(caminho) if os.path.isfile(os.path.join(caminho, f))]
    if not arquivos:
        messagebox.showinfo("Auto-Scan", "A pasta está vazia!")
        return

    novas_regras = {}

    for arquivo in arquivos:
        ext = os.path.splitext(arquivo)[1].lower()
        if not ext: continue

        achou_categoria = False
        for categoria, exts_preset in PRESETS.items():
            if ext in [e.strip() for e in exts_preset.split(',')]:
                nome_pasta = f"ORG_{categoria}"
                if nome_pasta not in novas_regras: novas_regras[nome_pasta] = []
                if ext not in novas_regras[nome_pasta]: novas_regras[nome_pasta].append(ext)
                achou_categoria = True
                break

        if not achou_categoria:
            if "ORG_Outros" not in novas_regras: novas_regras["ORG_Outros"] = []
            if ext not in novas_regras["ORG_Outros"]: novas_regras["ORG_Outros"].append(ext)

    # Atualiza a interface e o dicionário global
    regras_usuario.clear()
    list_regras.delete(0, END)
    for pasta, lista_ext in novas_regras.items():
        regras_usuario[pasta] = lista_ext
        list_regras.insert(END, f"📁 {pasta} ({len(lista_ext)} tipos)")

    messagebox.showinfo("Auto-Scan", "Escaneamento concluído! As regras sugeridas foram adicionadas.")


def ajuda_auto_scan():
    msg = (
        "O que o AUTO-SCAN faz?\n\n"
        "1. Analisa todos os arquivos da pasta selecionada.\n"
        "2. Identifica automaticamente as extensões.\n"
        "3. Organiza em pastas (Ex: Vídeos, Fotos) conforme nossos presets.\n"
        "4. Extensões desconhecidas vão para a pasta 'ORG_Outros'.\n\n"
        "Dica: Você pode editar ou remover as regras geradas antes de executar a faxina!"
    )
    messagebox.showinfo("Ajuda: Auto-Scan", msg)


def autocompletar(event):
    if event.keysym in ("BackSpace", "Left", "Right", "Up", "Down", "Shift_L", "Shift_R", "Control_L", "Return"):
        return
    texto_completo = ent_exts.get().lower()
    partes = texto_completo.split(',')
    ultima_parte = partes[-1].strip() if partes else ""
    if len(ultima_parte) < 1: return
    busca = ultima_parte if ultima_parte.startswith('.') else f".{ultima_parte}"
    for sugestao in TODAS_EXTENSOES:
        if sugestao.startswith(busca):
            posicao_cursor = ent_exts.index("insert")
            inicio_da_tag = posicao_cursor - len(ultima_parte)
            if not ultima_parte.startswith('.'):
                ent_exts.delete(inicio_da_tag, posicao_cursor)
                ent_exts.insert(inicio_da_tag, sugestao)
                ent_exts.selection_range(inicio_da_tag + len(ultima_parte) + 1, END)
            else:
                restante = sugestao[len(ultima_parte):]
                ent_exts.insert(posicao_cursor, restante)
                ent_exts.selection_range(posicao_cursor, END)
            break


def selecionar_pasta():
    pasta = filedialog.askdirectory()
    if pasta: lbl_caminho.config(text=f"{pasta}", fg="#2ecc71")


def carregar_preset(categoria):
    ent_pasta.delete(0, END)
    ent_exts.delete(0, END)
    ent_pasta.insert(0, f"ORG_{categoria}")
    ent_exts.insert(0, PRESETS[categoria])


def processar_tag_enter(event):
    texto_bruto = ent_exts.get().lower()
    if not texto_bruto: return
    texto_padronizado = texto_bruto.replace('.', ',').replace(' ', ',')
    tags = [f".{t.strip()}" for t in texto_padronizado.split(',') if t.strip()]
    novo_texto = ", ".join(tags)
    if novo_texto:
        ent_exts.delete(0, END)
        ent_exts.insert(0, f"{novo_texto}, ")


def adicionar_regra():
    nome_pasta = ent_pasta.get().strip()
    exts_bruto = ent_exts.get().strip().lower()
    if nome_pasta and exts_bruto:
        limpeza = exts_bruto.replace('.', ',').replace(' ', ',')
        lista_exts = [f".{t.strip()}" for t in limpeza.split(',') if t.strip()]
        if nome_pasta in regras_usuario:
            for i, item in enumerate(list_regras.get(0, END)):
                if item.startswith(f"📁 {nome_pasta}"):
                    list_regras.delete(i)
                    break
        regras_usuario[nome_pasta] = lista_exts
        list_regras.insert(END, f"📁 {nome_pasta} ({len(lista_exts)} tipos)")
        ent_pasta.delete(0, END)
        ent_exts.delete(0, END)
    else:
        messagebox.showwarning("Aviso", "Preencha os campos!")


def carregar_para_edicao(event):
    selecao = list_regras.curselection()
    if selecao:
        item_texto = list_regras.get(selecao)
        nome_pasta = item_texto.replace("📁 ", "").split(" (")[0]
        if nome_pasta in regras_usuario:
            ent_pasta.delete(0, END)
            ent_pasta.insert(0, nome_pasta)
            ent_exts.delete(0, END)
            ent_exts.insert(0, ", ".join(regras_usuario[nome_pasta]))


def remover_regra():
    selecao = list_regras.curselection()
    if selecao:
        item_texto = list_regras.get(selecao)
        nome_pasta_limpo = item_texto.replace("📁 ", "").split(" (")[0]
        if nome_pasta_limpo in regras_usuario: del regras_usuario[nome_pasta_limpo]
        list_regras.delete(selecao)
        ent_pasta.delete(0, END)
        ent_exts.delete(0, END)


def iniciar_organizacao():
    caminho = lbl_caminho.cget("text")
    if not os.path.exists(caminho) or caminho == "Nenhuma pasta selecionada":
        messagebox.showwarning("Aviso", "Selecione a pasta alvo!")
        return
    if not regras_usuario:
        messagebox.showwarning("Aviso", "Adicione regras!")
        return
    cont = 0
    lista_arquivos = os.listdir(caminho)
    for arquivo in lista_arquivos:
        origem = os.path.join(caminho, arquivo)
        if os.path.isdir(origem) or not os.path.exists(origem): continue
        ext = os.path.splitext(arquivo)[1].lower()
        for pasta, lista in regras_usuario.items():
            if ext in lista:
                dest_dir = os.path.join(caminho, pasta)
                os.makedirs(dest_dir, exist_ok=True)
                nome_final = arquivo
                base, extension = os.path.splitext(arquivo)
                i = 1
                while os.path.exists(os.path.join(dest_dir, nome_final)):
                    nome_final = f"{base} ({i}){extension}"
                    i += 1
                try:
                    shutil.move(origem, os.path.join(dest_dir, nome_final))
                    cont += 1
                    break
                except:
                    continue
    messagebox.showinfo("Sucesso", f"Faxina concluída! {cont} arquivos movidos.")


# --- INTERFACE ---
app = Tk()
app.title("PlexSweep")

try:
    with open("temp_icon.ico", "wb") as tmp_file:
        tmp_file.write(base64.b64decode(ICONE_VASSOURA_BASE64))
    app.iconbitmap("temp_icon.ico")
    os.remove("temp_icon.ico")
except:
    pass

app.geometry("700x650")  # Aumentei um pouco a altura para acomodar os botões
app.configure(bg="#121212")

Frame(app, bg="#2ecc71", height=5).pack(fill="x")
Label(app, text="CONFIGURAÇÃO PLEXSWEEP", font=("Arial", 14, "bold"), bg="#121212", fg="white", pady=15).pack()

# --- TOP FRAME (SELEÇÃO E AUTO-SCAN) ---
f_top = Frame(app, bg="#121212")
f_top.pack(pady=10)

lbl_caminho = Label(f_top, text="Nenhuma pasta selecionada", bg="#121212", fg="#888", width=40)
lbl_caminho.pack(side="left", padx=5)

Button(f_top, text="📂 SELECIONAR PASTA", command=selecionar_pasta, bg="#333", fg="white", font=("Arial", 9)).pack(
    side="left", padx=2)

# NOVO: Botão Auto-Scan
Button(f_top, text="🔍 AUTO-SCAN", command=auto_scan, bg="#2980b9", fg="white", font=("Arial", 9, "bold")).pack(
    side="left", padx=2)

# NOVO: Botão Ajuda (?)
Button(f_top, text="?", command=ajuda_auto_scan, bg="#444", fg="#bbb", width=2, font=("Arial", 9, "bold")).pack(
    side="left", padx=2)

main_frame = Frame(app, bg="#121212")
main_frame.pack(expand=True, fill="both", padx=20)

# COLUNA ESQUERDA
col_left = Frame(main_frame, bg="#1e1e1e", padx=15, pady=15)
col_left.pack(side="left", fill="both", expand=True, padx=5)

Label(col_left, text="1. Escolha um Preset:", bg="#1e1e1e", fg="#2ecc71", font=("Arial", 10, "bold")).pack(anchor="w")
f_presets = Frame(col_left, bg="#1e1e1e")
f_presets.pack(pady=10)

for p in PRESETS.keys():
    Button(f_presets, text=p, command=lambda cat=p: carregar_preset(cat), bg="#333", fg="white", font=("Arial", 8),
           width=15).pack(pady=2)

Label(col_left, text="2. Nome da Pasta:", bg="#1e1e1e", fg="white").pack(anchor="w", pady=(10, 0))
ent_pasta = Entry(col_left, bg="#333", fg="white", insertbackground="white", borderwidth=0)
ent_pasta.pack(fill="x", pady=5)

Label(col_left, text="3. Extensões (Tags):", bg="#1e1e1e", fg="white").pack(anchor="w")
ent_exts = Entry(col_left, bg="#333", fg="white", insertbackground="white", borderwidth=0)
ent_exts.pack(fill="x", pady=5)

ent_exts.bind('<Return>', processar_tag_enter)
ent_exts.bind('<KeyRelease>', autocompletar)

Button(col_left, text="ADICIONAR/ATUALIZAR REGRA", command=adicionar_regra, bg="#2ecc71", fg="black",
       font=("Arial", 9, "bold")).pack(fill="x", pady=15)

# COLUNA DIREITA
col_right = Frame(main_frame, bg="#1e1e1e", padx=15, pady=15)
col_right.pack(side="right", fill="both", expand=True, padx=5)

Label(col_right, text="Regras Ativas:", bg="#1e1e1e", fg="#2ecc71", font=("Arial", 10, "bold")).pack(anchor="w")
list_regras = Listbox(col_right, bg="#121212", fg="#eee", borderwidth=0, height=12, selectmode=SINGLE)
list_regras.pack(fill="both", expand=True, pady=10)
list_regras.bind('<<ListboxSelect>>', carregar_para_edicao)

Button(col_right, text="🗑️ APAGAR SELECIONADA", command=remover_regra, bg="#e74c3c", fg="white",
       font=("Arial", 8, "bold"), pady=5).pack(fill="x")

# --- RODAPÉ DE CRÉDITOS ---
lbl_dev = Label(app, text="Desenvolvido por Rodnei Júnior • 2026",
               bg="#121212", fg="#444", font=("Arial", 8))
lbl_dev.pack(side="bottom", pady=5)

# BOTÃO EXECUTAR (Mantenha ele acima do rodapé)
btn_run = Button(app, text="EXECUTAR FAXINA AGORA", command=iniciar_organizacao,
                 bg="#2ecc71", fg="black", font=("Arial", 12, "bold"),
                 pady=15, borderwidth=0)
btn_run.pack(fill="x", side="bottom")

app.mainloop()